# Generated by Django 3.1.5 on 2021-03-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_profile_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='member',
        ),
    ]
