# Generated by Django 3.1.5 on 2021-03-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_remove_profile_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member',
            field=models.IntegerField(max_length=2000, null=True),
        ),
    ]
